[package]
name = "tmt"
version = "0.1.0"
authors = ["Ryan Blecher <notryanb@gmail.com>"]
description = "A command line id3 tag management tool"
edition = "2018"

[dependencies]
id3 = "0.3"
structopt = "0.2"
walkdir = "2"
